# render.yaml

services:
  - type: web
    name: Spotify OBS Widget
    repo: https://github.com/Pikachubolk/SpotifyOBSWidget # Your GitHub repository
    branch: main # Branch to deploy from
    plan: free # Free plan
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: PORT
        value: '4000'
    autoDeploy: true # Automatically deploy changes from the specified branch
